### PR TITLE
Adds the --privileged flag to the instruction to run the agent docker…

### PR DESCRIPTION
**Pull request by sheroy**
...container

### CODE REVIEW

**Comment by arvindsv** [comment]
For https://github.com/gocd/docker-gocd-agent/issues/80

**Comment by varshavaradarajan** [comment]
This will be overwritten by https://github.com/gocd/docker-gocd-agent/blob/master/README.md.erb. So, any changes should be made there.

**Comment by arvindsv** [comment]
Damn it. You're right, @varshavaradarajan. But, we need the `--privileged` to be optional, used only in the dind image.

@GaneshSPatil or others: Where are flags such as `about_to_eol` (as in [here](https://github.com/gocd/docker-gocd-agent/blob/6180603d3f4f76a835dc5954b5bb0b840fe40fdd/README.md.erb#L5)) set? Can we set one specifically for this repo?

**Comment by ketan** [comment]
> Where are flags such as `about_to_eol` (as in [here](https://github.com/gocd/docker-gocd-agent/blob/6180603d3f4f76a835dc5954b5bb0b840fe40fdd/README.md.erb#L5)) set? Can we set one specifically for this repo?

https://github.com/gocd/docker-gocd-agent/blob/6180603d3f4f76a835dc5954b5bb0b840fe40fdd/Rakefile#L286

https://github.com/gocd/docker-gocd-agent/blob/6180603d3f4f76a835dc5954b5bb0b840fe40fdd/Rakefile#L89

**Comment by arvindsv** [comment]
Perfect. Thank you! @sheroy and I will make those changes tomorrow.

**Pull request merged**
