### PR TITLE
fixed linting and added --no-cache with apk add at a few places

### PR DESCRIPTION
**Pull request by vikas027**
I have fixed a few linting and other best practices like
- use `LABEL` instead of `MAINTAINER`
- apk add --no-cache
- `COPY` instead of `ADD`

### CODE REVIEW

**Comment by ghost** [comment]
[CLA assistant check](https://cla.gocd.org/gocd/docker-gocd-agent-dind?pullRequest=13) <br/>All committers have signed the CLA.

**Comment by vikas027** [comment]
Hey @varshavaradarajan  / @arvindsv ,

Can you please look at this PR? TIA.

I also think it is not a good idea to use the latest image `FROM alpine:latest`. What do you think?

**Comment by varshavaradarajan** [comment]
Making changes here will be overwritten by https://github.com/gocd/gocd/tree/master/buildSrc/src/main/resources/gocd-docker-agent. Please raise a PR against github.com/gocd/gocd for your changes. Thanks!

**Comment by vikas027** [comment]
> Making changes here will be overwritten by https://github.com/gocd/gocd/tree/master/buildSrc/src/main/resources/gocd-docker-agent. Please raise a PR against github.com/gocd/gocd for your changes. Thanks!

Hmm. The `Dockerfile` is a template with some if and else conditions, I have not used `.ftl` templates. Can you please point what templating language you guys have used? On a side note, I prefer using `jinja2` templates for such cases.

**Comment by arvindsv** [comment]
Not sure which linter is used, but I'd expect lines following a continuation in bash (backslash at end of line) should be indented by 2 spaces: https://github.com/gocd/docker-gocd-agent-dind/pull/13/files#diff-3254677a7917c6c01f55212f86c57fbfR66

The language used is Freemarker Templates, I believe: https://freemarker.apache.org/docs/dgui_quickstart_template.html

This might also be helpful: https://github.com/gocd/gocd/blob/7d250ee5047830bbca00d6e19ccc66c5f7e55900/buildSrc/src/main/groovy/com/thoughtworks/go/build/docker/Distro.groovy#L56

[Edit: Fixed last line]

**Comment by arvindsv** [comment]
Closing this, since there should be a different PR opened in gocd/gocd, as @varshavaradarajan mentioned. The conversation can continue here or there, of course.

**Comment by vikas027** [comment]
> Not sure which linter is used

I had used [hadolint](https://github.com/hadolint/hadolint)

> The language used is Freemarker Templates, I believe: https://freemarker.apache.org/docs/dgui_quickstart_template.html

Thanks for this, I will play around with it.

**Pull request closed without merging**
